## Comment for testing new
name: create_repo
on:
  push:
    branches:
      - main
      - 'feature/**'
env: 
  REPO_NAME: umami-app01-tier
  RUNNER_PATH: /home/runner/work/java-web/java-web/

jobs:
  build:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Create and Setup Repo
        working-directory: ./$REPO_NAME
        run: |
          echo $REPO_NAME
          sleep 5s
          cd $RUNNER_PATH
          mkdir $REPO_NAME    #this is the name of your directory
          cd $REPO_NAME
          git init
          touch $REPO_NAME/readme.md   #this is to create an initial file to push
          git commit -m "created new repo"
          sleep 10s


