## Comment for testing new
name: create_repo
on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  build:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: create repo
        run: |
          mkdir $repo_name    #this is the name of your directory
          cd $repo_name
          git init
          touch $repo_name/readme.md   #this is to create an initial file to push
          git commit -m "created new repo"
          sleep 10s


