## Comment for testing new
name: create_repo
on:
  push:
    branches:
      - main
      - 'feature/**'
env: 
  REPO_NAME: umami-app01-tier-13
  RUNNER_PATH: /home/runner/work/java-web/java-web/

jobs:
  build:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Create and Setup Repo
        #working-directory: ${{ github.workspace }}/scripts
        shell: bash
        run: |
          cd ${{ github.workspace }}/scripts
          # Change run modes to the scripts
          chmod +x ./create_repo.sh
          chmod +x ./clone_repo.sh
          
          # Run script for creating a repo
          ./create_repo.sh

          # Run script for cloning a repo
          ./clone_repo.sh

