## Comment for testing new
name: create_repo
on:
  push:
    branches:
      - main
      - 'feature/**'
env: 
  REPO_NAME: umami-app01-tier-13
  RUNNER_PATH: /home/runner/work/java-web/java-web/

jobs:
  build:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Create and Setup Repo
        run: |
          # Run script for creating a repo
          ../create_repo.sh

          git clone https://${{ secrets.TOKEN }}@github.com/jfechava-org/${{ env.REPO_NAME }}.git
          echo ${{ env.REPO_NAME }}
          cd ${{ env.REPO_NAME }}
          git init
          touch readme.md
          git add .
          git commit -m "Added new files to the new repo"
          git push 
              
  
