## Comment for testing new
name: create_repo
on:
  push:
    branches:
      - main
      - 'feature/**'
env: 
  REPO_NAME: umami-app01-tier-13
  RUNNER_PATH: /home/runner/work/java-web/java-web/

jobs:
  build:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Create and Setup Repo
        run: |
          #echo "The project name is:$REPO_NAME"
          #echo "The runner path is:$RUNNER_PATH"
          #echo "The TOKEN is:${{ secrets.TOKEN }}"
          mkdir ./$REPO_NAME
          #cd $REPO_NAME
          #git init
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          #touch readme.md
          #git add .
          #git commit -m "New repo"
          ##https://github.com/jfechava-org/java-web.git
          #git remote add origin git@github.com:jfechava/$REPO_NAME.git
          
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/orgs/jfechava-org/repos \
          -d '{"name":"${{ env.REPO_NAME }}","description":"New Repo from API","homepage":"https://github.com","private":false,"has_issues":true,"has_projects":true,"has_wiki":true}'

          git clone https://${{ secrets.TOKEN }}@github.com/jfechava-org/${{ env.REPO_NAME }}.git
          echo ${{ env.REPO_NAME }}
          cd ${{ env.REPO_NAME }}
          git init
          touch readme.md
          git add .
          git commit -m "Added new files to the new repo"
          git push 
              
  
