## Comment for testing new
name: create_repo
on:
  push:
    branches:
      - main
      - 'feature/**'
env: 
  REPO_NAME: umami-app01-tier
  RUNNER_PATH: /home/runner/work/java-web/java-web/

jobs:
  build:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Create and Setup Repo
        run: |
          echo "The project name is:$REPO_NAME"
          echo "The runner path is:$RUNNER_PATH"
          mkdir ./$REPO_NAME
          cd $REPO_NAME
          git init
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          touch readme.md
          git add .
          git commit -m "New repo"
          #git remote add origin git@github.com:jfechava/$REPO_NAME".git
     

