## Comment for testing new
name: create_repo
on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  build:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: create repo
        run: |
          mkdir 'umami-serv01-tier'    #this is the name of your directory
          cd 'umami-serv01-tier'
          git init
          sleep 10s


