## Comment for testing new
name: create_repo
on:
  push:
    branches:
      - main
      - 'feature/**'
env: 
  REPO_NAME: umami-app01-tier
  RUNNER_PATH: /home/runner/work/java-web/java-web/

jobs:
  build:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Create and Setup Repo
        run: |
          echo "The project name is:$REPO_NAME"
          echo "The runner path is:$RUNNER_PATH"
          mkdir ./$REPO_NAME
          cd $REPO_NAME
          touch readme.md
          ls
          pwd
     

