## Comment for testing new
name: main_pipeline
on:
  push:
    branches:
      - main
      #- 'feature/**'

jobs:
  build:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 15
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'
          java-version: '15'

      - name: Build with Maven
        run: mvn clean install



  test:

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3.13.0
        with:
           distribution: 'adopt'
           java-version: '15'

      - name: Test with Maven
        run: mvn test

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1.1.1
        with:
          credentials_json: '${{ secrets.JFE_SECRET }}' # optional
          cleanup_credentials: true

      # - name: Build and Push Docker image
      #   uses: docker/build-push-action@v5.0.0
      #   with:
      #     context: .
      #     file: Dockerfile
      #     platforms: linux/amd64
      #     tags: latest
      #     push: true

      - name: Install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: 'john-tests'
          service_account_key: ${{ secrets.JFE_SECRET }}
          export_default_credentials: true

      - name: Build and push Docker Image
        env:
          GOOGLE_PROJECT_N : ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker europe-southwest1-docker.pkg.dev
          docker build -t europe-southwest1-docker.pkg.dev/$GOOGLE_PROJECT_N/java-microservice/java-image:latest .
          docker push europe-southwest1-docker.pkg.dev/$GOOGLE_PROJECT_N/java-microservice/java-image:latest
