## Comment for testing
name: main_pipeline
on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  build:
    runs-on: 'ubuntu-20.04'   
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 15
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'
          java-version: '15'
      
      - name: Build with Maven
        run: mvn clean install



  test:

    runs-on: ubuntu-latest 
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'
          java-version: '15'
        
      - name: Test with Maven
        run: mvn test

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          tags: latest
          push: false 